<a href="https://colab.research.google.com/github/meghanlenskold/gb885-a4-world-health-pandas/blob/main/GB885_Assignment_4_Lenskold_M.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4

Scenario: You are an analyst for a global infant and maternal health advocacy group called JPG. Josephina, the groups founder, is preparing a presentation for the UN and has asked you to pull some insights for her from the data. You task is to use your understanding of Pandas to provide Josephina with the information she needs.

In [1]:
# Import libraries.
import numpy as np
import pandas as pd

In [2]:
# Create dataframes.
world_health_url = "https://raw.githubusercontent.com/katiegaertner/ML-Fundamentals/main/world-health-data-numbers.csv"
world_health_df = pd.read_csv(world_health_url)

In [3]:
# Question 1: How many rows are in the DataFrame you created?
# Question 2: How many columns are in the DataFrame you created?

world_health_df.shape

(194, 18)

In [4]:
# Preview first 5 columns.
world_health_df.head()

,Country,Pop_Density,Abbreviation,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
0,Andorra,164.0,AD,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
1,United Arab Emirates,118.0,AE,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
2,Afghanistan,60.0,AF,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
3,Antigua and Barbuda,223.0,AG,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
4,Albania,105.0,AL,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

In [5]:
# Set index.
world_health_df = world_health_df.set_index("Abbreviation")

world_health_df = world_health_df.sort_index()

world_health_df.head()

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
AD,Andorra,164.0,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
AE,United Arab Emirates,118.0,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
AF,Afghanistan,60.0,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
AG,Antigua and Barbuda,223.0,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
AL,Albania,105.0,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

In [6]:
# Question 3: What nation has the index value "DZ"?

world_health_df.loc["DZ"]

Country                               Algeria
Pop_Density                              18.0
Land_Area                           2381741.0
Birth_Rate                              24.28
CO2_Emissions                        150006.0
CPI                                    151.36
Fertility_Rate                           3.02
GDP                            169988000000.0
Infant mortality_per_1k                  20.1
Life_Expectancy                          76.7
Maternal_Mortality_per_100k             112.0
Minimum_Wage                             0.95
Official Language                      Arabic
oop_health_exp                           0.28
Physicians_per_1k                        1.72
Population                         43053054.0
Unemployment_Rate                        0.12
Name: DZ, dtype: object

In [7]:
# Drop Vatican City from our records.

world_health_df = world_health_df.drop("VA")

In [8]:
# Question 4: What is the official language of the nation on the 186th row?

world_health_df.iloc[185]["Official Language"]

'Spanish'

In [9]:
# Question 5: View the 10 nations with the highest infant mortality--what continent holds these ten nations?

world_health_df = world_health_df.sort_values("Infant mortality_per_1k", ascending=False)

world_health_df.head(10)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02
CD,Democratic Republic of the Congo,40.0,2344858.0,41.18,2021.0,133.85,5.92,4.731962e+10,68.2,60.4,473.0,0.18,French,0.37,0.07,86790567.0,0.04
LS,Lesotho,71.0,30355.0,26.81,2512.0,155.86,3.14,2.460072e+09,65.7,53.7,544.0,0.41,English,0.17,0.07,2125268.0,0.23
GN,Guinea,53.0,245857.0,36.36,2996.0,262.95,4.70,1.359028e+10,64.9,61.2,576.0,NaN,French,0.55,0.08,12771246.0,0.04
SS,South Sudan,18.0,644329.0,35.01,1727.0,4583.71,4.70,1.199780e+10,63.7,57.6,1150.0,NaN,English,0.61,NaN,11062113.0,0.12
GQ,Equatorial Guinea,50.0,28051.0,33.24,5655.0,124.35,4.51,1.102677e+10,62.6,58.4,301.0,1.05,Spanish,0.72,0.40,1355986.0,0.06

In [10]:
# Question 6: Create a new dataframe, but only for countries whose official language is Spanish. How many rows are in your new dataframe?

spanish_speaking_df = world_health_df[world_health_df["Official Language"] == "Spanish"]

spanish_speaking_df.shape

(19, 17)

In [11]:
# Question 7: What is the mean infant mortality per 1,000 infants in countries whose official language is Spanish?

print(spanish_speaking_df["Infant mortality_per_1k"].mean())

15.557894736842103

In [12]:
# Question 8: What is the median maternal mortality in countries whose official language is Spanish?

print(spanish_speaking_df["Maternal_Mortality_per_100k"].median())

65.0

In [13]:
# Question 9: Create a new column for GDP per capita, and identify the nation with fourth-highest GDP per capita.

world_health_df["GDP_Per_Capita"] = world_health_df["GDP"] / world_health_df["Population"]

world_health_df.sort_values("GDP_Per_Capita", ascending=False).head(5)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_Per_Capita
Abbreviation,,,,,,,,,,,,,,,,,,
MC,Monaco,26337.0,2.0,5.9,NaN,NaN,NaN,7.184844e+09,2.6,NaN,NaN,11.72,French,0.06,6.56,38964.0,NaN,184396.986783
LI,Liechtenstein,238.0,160.0,9.9,51.0,NaN,1.44,6.552859e+09,NaN,83.0,NaN,NaN,German,NaN,NaN,38019.0,NaN,172357.472290
LU,Luxembourg,242.0,2586.0,10.3,8988.0,115.09,1.37,7.110492e+10,1.9,82.1,5.0,13.05,Luxembourgish,0.11,3.01,645397.0,0.05,110172.373141
CH,Switzerland,219.0,41277.0,10.0,34477.0,99.55,1.52,7.030820e+11,3.7,83.6,5.0,NaN,German,0.28,4.30,8574832.0,0.05,81993.676378
RI,Republic of Ireland,72.0,70273.0,12.5,37711.0,106.58,1.75,3.886990e+11,3.1,82.3,5.0,10.79,Irish,0.15,3.31,5007069.0,0.05,77630.046640

In [14]:
# Question 10: What is the maternal mortality rate per 100,000 live births for that nation?

print(world_health_df.loc["CH", "Maternal_Mortality_per_100k"])

5.0

In [15]:
# Question 11: What is the the average maternal mortality rate per 100,000 for all nations in the data set?

print(world_health_df["Maternal_Mortality_per_100k"].mean())

160.39226519337018

In [16]:
# Question 12: What percentage of health care is paid out of pocket by country with the lowest infant mortality?

world_health_df.sort_values("Infant mortality_per_1k", ascending=True).head(1)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_Per_Capita
Abbreviation,,,,,,,,,,,,,,,,,,
FI,Finland,18.0,338145.0,8.6,45871.0,112.33,1.41,2.687610e+11,1.4,81.7,3.0,NaN,Swedish,0.2,3.81,5520314.0,0.07,48685.81751

In [17]:
# Question 13: What percentage of health care is paid out of pocket by country with the highest infant mortality?

world_health_df.sort_values("Infant mortality_per_1k", ascending=False).head(1)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_Per_Capita
Abbreviation,,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.4,0.06,4745185.0,0.04,467.907441